[package]
name = "brooke/roblox-project-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
iris = "michael-48/iris@2.3.1"
knit = "sleitnick/knit@1.7.0"
ui-labs = "rocky28447/ui-labs@0.1.0"
